"""empty message

Revision ID: 0a3714de2c4c
Revises: 7e96f5d8d90b
Create Date: 2020-01-11 20:10:14.401965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3714de2c4c'
down_revision = '7e96f5d8d90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('notes', sa.String(length=3000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'notes')
    # ### end Alembic commands ###
