"""empty message

Revision ID: 0b8efe2861a7
Revises: 65fcbcfd562a
Create Date: 2020-01-20 08:32:45.100749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8efe2861a7'
down_revision = '65fcbcfd562a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column('results', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column('results', sa.Column('middle_name', sa.String(length=20), nullable=True))
    op.add_column('results', sa.Column('nationality', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nationality')
    op.drop_column('results', 'nationality')
    op.drop_column('results', 'middle_name')
    op.drop_column('results', 'last_name')
    op.drop_column('results', 'first_name')
    # ### end Alembic commands ###
