"""empty message

Revision ID: 1a0b6fe528eb
Revises: d29b2582c399
Create Date: 2021-01-08 15:02:37.785532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0b6fe528eb'
down_revision = 'd29b2582c399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('buy_in_amount', sa.String(length=20), nullable=True))
    op.drop_column('tournaments', 'buy_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('buy_in', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'buy_in_amount')
    # ### end Alembic commands ###
