"""empty message

Revision ID: 1c0238f5890a
Revises: c1c3909ea332
Create Date: 2020-02-29 05:16:02.955240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0238f5890a'
down_revision = 'c1c3909ea332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('multiday_id', sa.String(length=15), nullable=True))
    op.add_column('flights', sa.Column('notes', sa.String(length=3000), nullable=True))
    op.add_column('tournaments', sa.Column('multiday_id', sa.String(length=15), nullable=True))
    op.drop_column('tournaments', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('notes', sa.VARCHAR(length=3000), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'multiday_id')
    op.drop_column('flights', 'notes')
    op.drop_column('flights', 'multiday_id')
    # ### end Alembic commands ###
