"""empty message

Revision ID: 29710b28d1e4
Revises: 
Create Date: 2019-12-21 03:04:23.150772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29710b28d1e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip_codes',
    sa.Column('zip_code', sa.String(length=14), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('zip_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zip_codes')
    # ### end Alembic commands ###
