"""empty message

Revision ID: 4c39bb07d23d
Revises: 95d9a5be056e
Create Date: 2020-03-07 20:18:05.655481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c39bb07d23d'
down_revision = '95d9a5be056e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casinos', sa.Column('facebook', sa.String(length=50), nullable=True))
    op.add_column('casinos', sa.Column('instagram', sa.String(length=50), nullable=True))
    op.add_column('casinos', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('casinos', sa.Column('twitter', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casinos', 'twitter')
    op.drop_column('casinos', 'phone')
    op.drop_column('casinos', 'instagram')
    op.drop_column('casinos', 'facebook')
    # ### end Alembic commands ###
