"""empty message

Revision ID: 4f61c5991620
Revises: e845182ae928
Create Date: 2021-09-01 16:25:14.815165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f61c5991620'
down_revision = 'e845182ae928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casinos', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casinos', 'online')
    # ### end Alembic commands ###
