"""empty message

Revision ID: 77bf1b25a2fa
Revises: 0a3714de2c4c
Create Date: 2020-01-15 21:06:49.594391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bf1b25a2fa'
down_revision = '0a3714de2c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('earnings', sa.String(length=100), nullable=True))
    op.drop_column('results', 'winning_prize')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('winning_prize', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('results', 'earnings')
    # ### end Alembic commands ###
