"""empty message

Revision ID: 782de9c2057d
Revises: f7385f5f13a8
Create Date: 2020-01-23 04:48:09.562978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782de9c2057d'
down_revision = 'f7385f5f13a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('starting_stack', sa.String(length=10), nullable=True))
    op.drop_column('tournaments', 'tarting_stack')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('tarting_stack', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'starting_stack')
    # ### end Alembic commands ###
