"""empty message

Revision ID: 7e96f5d8d90b
Revises: aeb1356d59d3
Create Date: 2019-12-28 13:39:16.903499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e96f5d8d90b'
down_revision = 'aeb1356d59d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zip_codes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip_codes',
    sa.Column('zip_code', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('zip_code', name='zip_codes_pkey')
    )
    # ### end Alembic commands ###
