"""empty message

Revision ID: 8fcf1fd63507
Revises: b9bf78d43ae7
Create Date: 2021-10-03 10:37:57.712147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcf1fd63507'
down_revision = 'b9bf78d43ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('profit_model', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'profit_model')
    # ### end Alembic commands ###
