"""empty message

Revision ID: 95d9a5be056e
Revises: 07944dc594ef
Create Date: 2020-03-07 00:44:34.784116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d9a5be056e'
down_revision = '07944dc594ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casinos', sa.Column('time_zone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casinos', 'time_zone')
    # ### end Alembic commands ###
