"""empty message

Revision ID: a5486c53b4c5
Revises: 36de6639c6e5
Create Date: 2021-04-15 11:13:02.974189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5486c53b4c5'
down_revision = '36de6639c6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('custom', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'custom')
    # ### end Alembic commands ###
