"""empty message

Revision ID: b9bf78d43ae7
Revises: fa8cc34bdf10
Create Date: 2021-10-03 10:37:18.914844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bf78d43ae7'
down_revision = 'fa8cc34bdf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'profit_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('profit_model', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
