"""empty message

Revision ID: cd681db3a1f5
Revises: 1a0b6fe528eb
Create Date: 2021-01-09 14:04:01.876373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd681db3a1f5'
down_revision = '1a0b6fe528eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('results_user_id_fkey', 'results', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('results_user_id_fkey', 'results', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
