"""empty message

Revision ID: dcb595a4d866
Revises: 747f11193881
Create Date: 2020-01-23 05:41:47.981175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb595a4d866'
down_revision = '747f11193881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('blinds', sa.String(length=20), nullable=True))
    op.drop_column('tournaments', 'linds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('linds', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'blinds')
    # ### end Alembic commands ###
