"""empty message

Revision ID: ea36832827b7
Revises: 323d9d88f036
Create Date: 2019-12-20 07:20:50.300432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea36832827b7'
down_revision = '323d9d88f036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('structure_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'structure_link')
    # ### end Alembic commands ###
