"""empty message

Revision ID: eb0af20ad97e
Revises: 782de9c2057d
Create Date: 2020-01-23 04:54:46.531433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0af20ad97e'
down_revision = '782de9c2057d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casinos', 'h1')
    op.add_column('tournaments', sa.Column('h1', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'h1')
    op.add_column('casinos', sa.Column('h1', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
