"""empty message

Revision ID: fa8cc34bdf10
Revises: 4f61c5991620
Create Date: 2021-10-03 10:22:13.133377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8cc34bdf10'
down_revision = '4f61c5991620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('profit_model', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'profit_model')
    # ### end Alembic commands ###
